DEFAULT_LOG_LEVEL = "INFO"

DEFAULT_MIN_VALUE = "-1"
DEFAULT_MAX_VALUE = "100"
DEFAULT_MAX_BUFFER_SIZE = "5"

DEFAULT_SENSOR_AREA = "LIVING_ROOM"
DEFAULT_SENSOR_TYPE = "TEMPERATURE"
DEFAULT_READ_INTERVAL_SECONDS = "1"

DEFAULT_MQTT_HOST = "localhost"
DEFAULT_MQTT_PORT = "1883"
